#群组模式
BungeeCordMode: false

#喇叭设置
HornSettings:
  #自定义名称
  普通喇叭:
    #命令列表
    Commands:
      - "shout"
    #权限
    Permission: "MHDFShout.Shout.DefaultShout"
    #队列系统（等待上一个喇叭消失后显示新喇叭）
    Wait: true
    #解析颜色符号
    Color: true
    #喊话背景贴图
    NullBossBarMessage: "뛣"
    #字数限制 (-1关闭)
    MaxLength: 20
    #显示时长
    ShowTime: 15
    #Boss血条颜色
    BossBarColor: YELLOW
    #文本格式
    MessageFormat: "&f뢆 &f%luckperms_prefix% %player_name% &f{Message}"
    #音效 [<音频>|<音量|<音效>]
    Sound: "ENTITY_WOLF_AMBIENT|25|0.9"
  #自定义名称
  胡桃喇叭:
    #命令列表
    Commands:
      - "hutaoshout"
    #权限
    Permission: "MHDFShout.Shout.HuTaoShout"
    #队列系统（等待上一个喇叭消失后显示新喇叭）
    Wait: true
    #解析颜色符号
    Color: true
    #喊话背景贴图
    NullBossBarMessage: "륣"
    #字数限制 (-1关闭)
    MaxLength: 20
    #显示时长
    ShowTime: 15
    #Boss血条颜色
    BossBarColor: YELLOW
    #文本格式
    MessageFormat: "&f뢆 &f%luckperms_prefix% %player_name% &f{Message}"
    #音效 [<音频>|<音量|<音效>]
    Sound: "ENTITY_VILLAGER_AMBIENT|25|0.9"
  #自定义名称
  兔子喇叭:
    #命令列表
    Commands:
      - "tuzishout"
    #权限
    Permission: "MHDFShout.Shout.TuZiShout"
    #队列系统（等待上一个喇叭消失后显示新喇叭）
    Wait: true
    #解析颜色符号
    Color: true
    #喊话背景贴图
    NullBossBarMessage: "뜄"
    #字数限制 (-1关闭)
    MaxLength: 20
    #显示时长
    ShowTime: 15
    #Boss血条颜色
    BossBarColor: YELLOW
    #文本格式
    MessageFormat: "&f뢆 &f%luckperms_prefix% %player_name% &f{Message}"
    #音效 [<音频>|<音量|<音效>]
    Sound: "ENTITY_RABBIT_DEATH|25|0.9"
  #自定义名称
  蛋蛋喇叭:
    #命令列表
    Commands:
      - "dandanshout"
    #权限
    Permission: "MHDFShout.Shout.DanDanShout"
    #队列系统（等待上一个喇叭消失后显示新喇叭）
    Wait: true
    #解析颜色符号
    Color: true
    #喊话背景贴图
    NullBossBarMessage: "냊"
    #字数限制 (-1关闭)
    MaxLength: 20
    #显示时长
    ShowTime: 15
    #Boss血条颜色
    BossBarColor: YELLOW
    #文本格式
    MessageFormat: "&f뢆 &f%luckperms_prefix% %player_name% &f{Message}"
    #音效 [<音频>|<音量|<音效>]
    Sound: "ENTITY_CHICKEN_EGG|25|0.9"
  #自定义名称
  凋零玫瑰喇叭:
    #命令列表
    Commands:
      - "diaolingshout"
    #权限
    Permission: "MHDFShout.Shout.DiaoLingShout"
    #队列系统（等待上一个喇叭消失后显示新喇叭）
    Wait: true
    #解析颜色符号
    Color: true
    #喊话背景贴图
    NullBossBarMessage: "냁"
    #字数限制 (-1关闭)
    MaxLength: 20
    #显示时长
    ShowTime: 15
    #Boss血条颜色
    BossBarColor: YELLOW
    #文本格式
    MessageFormat: "&f뢆 &f%luckperms_prefix% %player_name% &f{Message}"
    #音效 [<音频>|<音量|<音效>]
    Sound: "ENTITY_WITHER_AMBIENT|25|0.9"
  #自定义名称
  管理喊话:
    #命令
    Commands:
      - "adminshout"
    #权限
    Permission: "MHDFShout.Shout.AdminShout"
    #队列系统（等待上一个喇叭消失后显示新喇叭）
    Wait: false
    #解析颜色符号
    Color: true
    #喊话背景贴图
    NullBossBarMessage: "륣"
    #字数限制 (-1关闭)
    MaxLength: -1
    #显示时长
    ShowTime: 15
    #Boss血条颜色
    BossBarColor: YELLOW
    #文本格式
    MessageFormat: "&c[管理全服喊话] &f{Message}"
    #音效 [<音频>|<音量|<音效>]
    Sound: "ENTITY_WITHER_SPAWN|25|0.9"

#喊话设置
ShoutSettings:
  #冷却 (-1关闭)
  Delay: 5
  #屏蔽词列表
  BlackWordList:
    - "傻逼"
